name: AI CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check project files
        run: |
          pwd
          ls -la
          echo "=== CSV Data ==="
          ls -la Tanseek_CSV_Data

      - name: Run tests
        run: pytest